name: cfm
description: A new Flutter project.


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_database: ^2.0.3
  image_picker: ^0.5.0+3
  firebase_storage: ^2.1.0+1
  date_format: ^1.0.6
  carousel_pro: ^0.0.13
  firebase_core: ^0.3.4

 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/cfm.png
    - assets/alucard.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf


  

  # flutter_icons:
  # android: "launcher_icon" 
  # # ios: true
  # image_path: "assets/icon/ic_launcher-web.png"